import {test, expect} from '@playwright/test';
import {fixture, postLog, rerender} from './review-fixtures.js';

test('Feed Baby offers independent scrollable amounts and preserves them through editing', async ({page}) => {
  const {headers} = await fixture(page);
  expect((await page.request.post('/api/chores/seed-defaults', {headers})).ok()).toBeTruthy();
  const {chores} = await (await page.request.get('/api/chores')).json();
  const chore = chores.find(chore => chore.name === 'Feed Baby');
  await page.reload();
  await page.locator(`[data-home-chore-id="${chore.id}"]`).click();
  const formula = page.getByRole('combobox', {name: 'Choose 🍼 formula amount', exact: true, includeHidden: true});
  const breast = page.getByRole('combobox', {name: 'Choose 🤱 breast amount', exact: true, includeHidden: true});
  await expect(formula).toBeVisible();
  await expect(breast).toBeHidden();
  await formula.selectOption('120');
  await page.getByRole('button', {name: '🤱 breast', exact: true}).click();
  await breast.selectOption('30');
  await page.getByRole('button', {name: '🍼 formula', exact: true}).click();
  await expect(formula).toBeHidden();
  await expect(formula).toBeDisabled();
  await page.getByRole('button', {name: '🍼 formula', exact: true}).click();
  await expect(formula).toHaveValue('120');
  await rerender(page);
  await expect(formula).toHaveValue('120');
  await expect(breast).toHaveValue('30');
  await page.locator('[data-action="save-log"]').click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  const {logs} = await (await page.request.get('/api/logs/history')).json();
  const log = logs.find(log => log.choreId === chore.id);
  expect(log.indicatorVolumes).toEqual({'🍼 formula': 120, '🤱 breast': 30});
  await page.locator('[data-nav="activity"]').click();
  await page.locator(`[data-action="view-log"][data-log-id="${log.id}"]`).click();
  await expect(formula).toHaveValue('120');
  await expect(breast).toHaveValue('30');
  await formula.selectOption('125');
  await page.getByRole('button', {name: 'Cancel', exact: true}).click();
  await page.locator(`[data-action="view-log"][data-log-id="${log.id}"]`).click();
  await expect(formula).toHaveValue('120');
});

test('custom activity amounts keep typed values, units, recent values and zero in sync', async ({page}) => {
  const {chore} = await fixture(page, {name: 'Medication', metricUnit: 'mg'});
  const previous = await postLog(page, chore, {volumeML: 37, metricUnit: 'mg'});
  await page.reload();
  await page.locator(`[data-home-chore-id="${chore.id}"]`).click();
  const input = page.getByLabel('Amount', {exact: true});
  const picker = page.getByRole('combobox', {name: 'Choose amount', exact: true});
  const unit = page.getByLabel('Unit', {exact: true});
  await page.locator('.volume-recent-chip').click();
  await expect(picker).toHaveValue('37');
  await input.fill('12345');
  await expect(picker).toHaveValue('12345');
  await unit.selectOption('tablets');
  await expect(input).toHaveValue('12345');
  await expect(picker).toHaveValue('12345');
  await expect(picker.locator('option:checked')).toHaveText('12345 tablets');
  await picker.selectOption('0');
  await expect(input).toHaveValue('0');
  await picker.selectOption('');
  await expect(input).toHaveValue('');
  await picker.selectOption('2');
  await page.locator('[data-action="save-log"]').click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const {logs} = await (await page.request.get('/api/logs/history')).json();
  expect(logs.find(log => log.id !== previous.id)).toMatchObject({volumeML: 2, metricUnit: 'tablets'});
});

test('number choices can save zero and clear an existing amount', async ({page}) => {
  const {chore} = await fixture(page);
  await page.locator(`[data-home-chore-id="${chore.id}"]`).click();
  const picker = page.getByRole('combobox', {name: 'Choose amount', exact: true});
  const input = page.getByLabel('Amount', {exact: true});
  await picker.selectOption('0');
  await expect(input).toHaveValue('0');
  await page.locator('[data-action="save-log"]').click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  const {logs} = await (await page.request.get('/api/logs/history')).json();
  expect(logs[0].volumeML).toBe(0);
  await page.locator('[data-nav="activity"]').click();
  await page.locator(`[data-action="view-log"][data-log-id="${logs[0].id}"]`).click();
  await picker.selectOption('');
  await page.locator('[data-action="save-log"]').click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  const updated = await (await page.request.get('/api/logs/history')).json();
  expect(updated.logs[0].volumeML ?? null).toBeNull();
});

test('ounce choices convert once and preserve exact stored amounts on edit', async ({page}) => {
  const {chore} = await fixture(page, {name: 'Bottle', metricUnit: 'mL'});
  const log = await postLog(page, chore, {volumeML: 37, metricUnit: 'oz'});
  await page.reload();
  await page.locator('[data-nav="activity"]').click();
  await page.locator(`[data-action="view-log"][data-log-id="${log.id}"]`).click();
  const picker = page.getByRole('combobox', {name: 'Choose amount', exact: true});
  const input = page.getByLabel('Amount', {exact: true});
  await expect(picker).toHaveValue(await input.inputValue());
  await page.locator('[data-action="save-log"]').click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  let history = await (await page.request.get('/api/logs/history')).json();
  expect(history.logs.find(entry => entry.id === log.id).volumeML).toBe(37);
  await page.locator(`[data-action="view-log"][data-log-id="${log.id}"]`).click();
  await picker.selectOption('2.5');
  await expect(input).toHaveValue('2.5');
  await page.locator('[data-action="save-log"]').click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  history = await (await page.request.get('/api/logs/history')).json();
  expect(history.logs.find(entry => entry.id === log.id)).toMatchObject({volumeML: 74, metricUnit: 'oz'});
});

test('duration choices and exact typed seconds persist and enforce the existing range', async ({page}) => {
  const {chore} = await fixture(page, {name: 'Walk', metricType: 'duration', metricUnit: ''});
  await page.locator(`[data-home-chore-id="${chore.id}"]`).click();
  const picker = page.getByRole('combobox', {name: 'Choose duration', exact: true});
  const input = page.getByLabel('Duration (seconds)', {exact: true});
  await picker.selectOption('300');
  await expect(input).toHaveValue('300');
  await input.fill('301');
  await expect(picker).toHaveValue('301');
  await input.fill('86401');
  await page.locator('[data-action="save-log"]').click();
  await expect(page.getByRole('dialog')).toHaveCount(1);
  await input.fill('301');
  await page.locator('[data-action="save-log"]').click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  const {latestLogs} = await (await page.request.get('/api/logs/latest-per-chore')).json();
  expect(latestLogs[chore.id].durationSeconds).toBe(301);
  await page.locator('[data-nav="activity"]').click();
  await page.locator(`[data-action="view-log"][data-log-id="${latestLogs[chore.id].id}"]`).click();
  await expect(input).toHaveValue('301');
  await expect(picker).toHaveValue('301');
});
