ALTER TABLE chores ADD COLUMN IF NOT EXISTS follow_up_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chores ADD COLUMN IF NOT EXISTS last_follow_up_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE chore_schedules ADD COLUMN IF NOT EXISTS is_follow_up BOOLEAN NOT NULL DEFAULT FALSE;
